/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as multiPairAmmSol from "./MultiPairAMM.sol";
export type { multiPairAmmSol };
import type * as simpleAmmSol from "./SimpleAMM.sol";
export type { simpleAmmSol };
import type * as vaultManagerSol from "./VaultManager.sol";
export type { vaultManagerSol };
export type { AgentIdentityRegistry } from "./AgentIdentityRegistry";
export type { FollowerRegistry } from "./FollowerRegistry";
export type { Greeting } from "./Greeting";
export type { MockMETH } from "./MockMETH";
export type { MockWETH } from "./MockWETH";
export type { MockWMNT } from "./MockWMNT";
export type { AUSD } from "./AUSD";
